### PR TITLE
Use images with openssl already installed

### PR DESCRIPTION
**Pull request by SeanTAllen**
Switch to testing on alpine based images that already have ssl installed.

### CODE REVIEW

**Comment by SeanTAllen** [comment]
@Theodus is this failing because I switched over to testing using an alpine based image rather than glibc and the test script installs the non-alpine version? if yes, i'll leave this open for now and we can merge once we have alpine support via ponyup in place.

**Comment by SeanTAllen** [comment]
@Theodus this is ready for review.

**Comment by Theodus** [comment]
@SeanTAllen should we also remove `install-openssl.sh`?

**Comment by SeanTAllen** [comment]
@Theodus yeah, ill do that before merging.

**Pull request merged**
