### PR TITLE
Remove temporary appdirs location fix

### PR DESCRIPTION
**Pull request by SeanTAllen**
Once the next nightly is in place, this will work correctly.

### CODE REVIEW

**Comment by SeanTAllen** [comment]
After the next nightly is in place, we can rerun this to verify that bootstrap is working and then merge.

**Comment by SeanTAllen** [comment]
@Theodus looks like something else broke with the macOS bootstrapping with this change.

```
error: unexpected selection: ponyc-nightly-x86_64-apple-darwin19.0.0
error: unexpected selection: changelog-tool-nightly-x86_64-apple-darwin19.0.0
error: unexpected selection: corral-nightly-x86_64-apple-darwin19.0.0
error: unexpected selection: stable-nightly-x86_64-apple-darwin19.0.0
```

**Comment by Theodus** [comment]
It looks like `x86_64-apple-darwin19.0.0` is the triple given by `cc -dumpmachine`. That's not what I would expect if so.

**Comment by SeanTAllen** [comment]
@Theodus I think we want something like what we are doing here:

https://github.com/ponylang/ponyup/blob/master/ponyup-init.sh#L40

Check the dumpmachine output for expected values (probably a regex) and then if we don't get expected, error out.

**Comment by SeanTAllen** [comment]
@Theodus building on that idea, perhaps we remove the uname check and replace with a dumpmachine check. But first, we should verify that `cc` exists and error out if it isn't available.

**Comment by SeanTAllen** [comment]
@Theodus OR...

we only do the dumpmachine check on Linux and otherwise for other platforms. write out a known value to `.platform` based on uname as only Linux needs the dumpmachine check.

**Pull request merged**
