### PR TITLE
Update bootstrap environments

### PR DESCRIPTION
**Pull request by SeanTAllen**
We need clang to be installed with most recent ponyc as it uses
clang as the default linker.

Also, update to Ubuntu 20.04 as we no longer support 18.04

### CODE REVIEW

**Comment by SeanTAllen** [comment]
@Theodus I can't build the ubuntu image locally at the moment. I get an error that appears to be regional in nature as when the ponyc release docker image was built earlier, it had no problems.

Can you give it a try?

My error:

"E: Release file for http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease is not valid yet (invalid for another 2h 22min 57s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease is not valid yet (invalid for another 2h 23min 0s). Updates for this repository will not be applied."

**Comment by SeanTAllen** [comment]
Also the libz error on Fedora, that is odd. I wonder what that requirement is coming from.

@Theodus do you have time to check the fedora error and see if ponyc requires libz.so to run (i hope not!) or if it is an odd unsatisfied dependency we are missing for building ponyup in fedora environments?

**Comment by SeanTAllen** [comment]
I got the ubuntu image building working. I needed to restart my computer because... of course I did.

**Comment by SeanTAllen** [comment]
The fedora error is because of this with the glibc builds (note this is on ubuntu 18.04)

./ponyc: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./ponyc)
        linux-vdso.so.1 (0x00007ffe5416c000)
        libatomic.so.1 => /usr/lib/x86_64-linux-gnu/libatomic.so.1 (0x00007fe17dca9000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe17daa5000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fe17d888000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fe17d680000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe17d461000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe17d0c3000)
        libz3.so.4 => not found
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fe17ceab000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe17caba000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fe17deb1000)

**Comment by SeanTAllen** [comment]
@Theodus are you ok with turning off Fedora bootstrap while we discuss "the glibc issue" at sync this week? If yes, I will update this and get your sign-off so we can move forward with some other PRs.

**Comment by Theodus** [comment]
@SeanTAllen That sounds good

**Comment by Theodus** [comment]
See https://github.com/ponylang/ponyc/issues/3537

**Pull request merged**
