### PR TITLE
Detect platform identifier with init script

### PR DESCRIPTION
**Pull request by Theodus**
Detect platform using a `.platform` config file created by the init script. This also cleans up much of the code for the `show` command and adds tests for the platform string parsing.

With this change, supplying `--platform=musl` on musl-based Linux distros like Alpine should no longer be required as "musl-based" should be detected when ponyup is installed. 

If ponyup is upgraded from an earlier version without using the init script, then this change will have no impact and `--platform=musl` will continue to be needed.

### CODE REVIEW

**Comment by SeanTAllen** [comment]
There are a couple of issues right now:

- Detect isn't working on macOS.
- bootstrap test isn't installing in the usual /root/.local/ on Linux. the install location isn't in the PATH so stable can't be found.

**Comment by SeanTAllen** [comment]
@Theodus are you thinking with this that we have 2 ponyup packages for Linux, one for musl, one for gnu and folks download the one that is appropriate for their distro?

**Comment by SeanTAllen** [comment]
@Theodus I'm having reservations about this. 

The problem:

We need to link to libSSL. If we also link to Glibc, then we have to dynamically link the SSL lib. The statically linked binaries are very nice. Having a single ponyup is very nice. I think that linking against Glibc might be worse than having musl users have to give their platform. Rustup defaults to Glibc and requires you to explicitly request musl.

I like the bootstrap testing changes that have been added to this PR. I think we should definitely keep them in some form (they already found a bug).

Ideas:

- Leave as-is with having to supply platform to get `musl` version of Pony
- On Linux, in the ponyup directory, store some configuration for the platform to use. If config isn't set, then we prompt the user to supply it unless `--platform` was explicitly provided. If provided, we could save the selected platform and use it as the default in the future. 
- Shell out to `cc -dumpmachine` until such time as we don't use cc for linking.

**Comment by Theodus** [comment]
@SeanTAllen I agree with your concerns. I'll remove the libc detection bits from this PR and add go forward with expecting the user to provide the libc in `--platform`.

**Comment by SeanTAllen** [comment]
@Theodus what are your thoughts on trying to detect at the time we do pony-init.sh on the user's machine and writing that out to a config?

**Comment by Theodus** [comment]
@SeanTAllen I'll add that now that I've fixed the platform parsing (the problem with Alpine was that the vendor part of the target triple was `alpine`).

**Comment by SeanTAllen** [comment]
@Theodus the bootstrap needs  "--platform=$(cc -dumpmachine)" so that it knows which platform it is on. Is there a reason you removed it? At the moment, the alpine test is installing the GNU version as it is the default.

**Comment by SeanTAllen** [comment]
Parse platform test is failing on macOS.

**Comment by Theodus** [comment]
> @Theodus the bootstrap needs "--platform=$(cc -dumpmachine)" so that it knows which platform it is on. Is there a reason you removed it? At the moment, the alpine test is installing the GNU version as it is the default.

The init script will set the platform, which should get picked up by ponyup

**Comment by SeanTAllen** [comment]
@Theodus ok, in that case, it isn't working as the alpine test is still pulling GNU.

**Comment by Theodus** [comment]
> @Theodus ok, in that case, it isn't working as the alpine test is still pulling GNU.

I think that's because it's not downloading the ponyup from this PR with the init script, since it hasn't been built to support that yet.

**Comment by SeanTAllen** [comment]
@Theodus you are right, i think we need to leave --platform in for this PR and once it is merged and we have a new nightly, we can do another PR to remove --platform and fully verify that it is working.

**Comment by SeanTAllen** [comment]
@Theodus a right, this still won't pass the bootstrap test because, it doesn't understand the dump machine either. So, ya, drop the dumpmachine and we can open another PR to make sure its fully working after this is merged and there's a new nightly.

**Comment by SeanTAllen** [comment]
actually @Theodus I have an idea.

let's have a temporary alpine bootstrap that does `--platform=musl` and we can replace after the next nightly. 

i'll do that now.

**Comment by Theodus** [comment]
Sorry I think I just trampled over you with that force push. Is this what you did?

**Comment by SeanTAllen** [comment]
@Theodus you just wiped out my changes, yes

**Comment by SeanTAllen** [comment]
@Theodus let me put them back as you didnt get it right.

**Comment by Theodus** [comment]
Sorry, I'll redo yours

**Comment by Theodus** [comment]
Ok, you do it

**Comment by SeanTAllen** [comment]
@Theodus ok, the temporary -musl bootstrap test is in, once this is merged, it can be removed via PR after the next nightly to verify everything fully works.

**Comment by SeanTAllen** [comment]
@Theodus I updated the PR comment with additional info. If there is anything else you think should be added to it, please do and we can use that comment as the commit comment when we squash and merge.

**Comment by Theodus** [comment]
Looks good to me. I should probably remove the bit about needing `--platform` on musl from the README

**Comment by SeanTAllen** [comment]
@Theodus ya and the README update for ponyc, I'll update that as well. And we can merge that after the next ponyup release (which I plan to do before the end of the year).

**Comment by SeanTAllen** [comment]
@Theodus should the bootstrap test be running `make test` or just `make`. I'm not sure what we get out of doing `make test`. I'm thinking we should only do `make`.

**Comment by Theodus** [comment]
Just make seems fine to me

**Comment by SeanTAllen** [comment]
@Theodus are these failures at this point because not all the tools have macOS releases yet? The error messages are really obscure at this point, we should definitely improve them. It's unclear to me what the failures are.

**Comment by Theodus** [comment]
They are a result of the packages not being available

**Comment by SeanTAllen** [comment]
@Theodus what do you think of breaking the tests apart so that release and nightly are different? that would be a bit more clear.

it appears that release tests are hardcoded to specific versions. what is the idea with that? is it recent releases, any releases, all releases? what is your thought for those.

**Comment by Theodus** [comment]
Only the select test has hard coded versions. The sync tests are a port from the shell script and uses the 2 most recent nightly and release builds.

**Comment by SeanTAllen** [comment]
What about `ifdef`ing the tests that will fail on macOS for now and create an issue to update them once they will pass by removing the `ifdef` and updating the versions?

**Comment by Theodus** [comment]
Good idea, I always forget that pony has ifdefs

**Comment by Theodus** [comment]
All CI tests are passing now except for the macOS bootstrap (which we expect to fail)

**Comment by SeanTAllen** [comment]
Merged. After tonight's nightly we should be able to remove the temporary musl script.

@Theodus can you open an issue to remove the `ifdef`s in the future once they are no longer needed?

**Pull request merged**
