### PR TITLE
Select uses latest version if none is specified

### LINKED ISSUE #85: Select fails on `latest` version
Select only works when the full version number is given. The select command should be modified to search the lockfile and choose the highest version number available.

See #84 for context.

### PR DESCRIPTION
**Pull request by Theodus**
Closes #85

### CODE REVIEW

**Comment by SeanTAllen** [comment]
Can you manually add release notes to "next-release.md" as I haven't completed all the work on that yet?

**Comment by SeanTAllen** [comment]
@Theodus with https://github.com/ponylang/ponyup/pull/140 merged, you can add a "regular release notes" file like "139.md" rather than modifying "next-release.md" directly and we can verify that works.

**Comment by SeanTAllen** [comment]
Release notes look good @Theodus. Any thoughts on test(s)?

**Comment by Theodus** [comment]
The select command is currently tested through the automatic select that happens on update, so there isn't an easy way to add a test for this feature. Note for #48

**Comment by Theodus** [comment]
@SeanTAllen I don't think the release notes bot worked

**Comment by SeanTAllen** [comment]
@Theodus yup. im a dumbass. can you...

1) remove your file and manually update next-release.md
2) rename .release_notes to .release-notes

thanks.

**Comment by Theodus** [comment]
fixed: f67d4fd

**Pull request merged**
