### PR TITLE
Turn on select test for FreeBSD

### LINKED ISSUE #124: Enable select test for BSD
The `select` test requires another release of ponyc with the `freebsd-12.1` versioning scheme. Once another release is out, remove the platform check in https://github.com/ponylang/ponyup/blob/81e3d7f94478637d1b1fa0c53dc6a89c49f71879/test/main.pony#L22

### PR DESCRIPTION
**Pull request by SeanTAllen**
Closes #124

### CODE REVIEW

**Comment by SeanTAllen** [comment]
@Theodus I think this explains the bug that @Erk- reported in Zulip.

**Comment by SeanTAllen** [comment]
@Theodus I think this explains the bug that @Erk- reported in Zulip. 

It is incorrectly parsing as freebsd12.1 instead of freebsd-12.1 that it needs to look for.

freebsd12.1 is what it was originally but we switched to freebsd-12.1

**Comment by SeanTAllen** [comment]
@Theodus do you think this broke with the ubuntu18.04 addition? We don't have a test for ubuntu18.04, we should probably add one as part of fixing this so we don't end up regularly breaking them.

**Comment by Theodus** [comment]
@SeanTAllen the ubuntu packages work fine, as far as I can tell from fetching them locally. See #162 for a fix to the Cloudsmith queries for FreeBSD

**Comment by Theodus** [comment]
I'm not sure where `-freebsd-freebsd12.1` is coming from

**Comment by Theodus** [comment]
Ah, I see. The Makefile is setting the `PONYUP_PLATFORM` env on FreeBSD using `cc -dumpmachine`. So either make a special case in the Makefile for FreeBSD or add `PONYUP_PLATFORM=PONYUP_PLATFORM=x86_64-unknown-freebsd-12.1` to the gmake invocation

**Comment by SeanTAllen** [comment]
@Theodus so basically, we sort of messed up naming with the triple?

**Comment by SeanTAllen** [comment]
I'd say we special case in the Makefile.

**Comment by Theodus** [comment]
> @Theodus so basically, we sort of messed up naming with the triple?

No, `cc -dumpmachine` not giving a sensible result across platforms is the reason why we go through so much trouble with parsing platform identifiers.

> I'd say we special case in the Makefile.

Ok, using a combination of `freebsd-version` and other things rather than just `cc -dumpmachine` is probably the way to go for FreeBSD.

**Comment by SeanTAllen** [comment]
@Theodus Am i correct in assuming you will be taking over this PR and getting it to pass?

**Comment by Theodus** [comment]
I don't have easy access to a FreeBSD box right now, so it may take me a few days

**Comment by SeanTAllen** [comment]
@Theodus Neither do I. I've been relying on CI.

**Pull request merged**
