### PR TITLE
Add support for release channel

### PR DESCRIPTION
**Pull request by Theodus**
The release channel for ponyc can now be installed with `update`. The format of the `update` command now requires the package to be specified prior to the version argument. The `show` command now lists the installed packages rather than showing the output of `ponyc --version`.

### CODE REVIEW

**Comment by Theodus** [comment]
Once this PR is merged, a new issue should be added for marking the selected packages and listing packages available on Cloudsmith in the output of `show`.

**Comment by SeanTAllen** [comment]
So right now for building latest docker images we do:

ponyup nightly

and get everything.

how would that change once this is merged?

**Comment by Theodus** [comment]
> This should update the CHANGELOG.
> 
> I think the change from version 0.1.0 to 0.2.0 should be in another commit where we actually version by tagging etc.

Do you think that that commit should be included in this PR?

**Comment by SeanTAllen** [comment]
not anymore! we can use the changelog bot!

**Comment by Theodus** [comment]
> So right now for building the latest docker images, we do:
> 
> * `ponyup update nightly`
> 
> and get "everything"
> 
> * ponyc
> * stable
> * corral
> 
> how would that change once this is merged?
> 
> See https://github.com/ponylang/ponyc/tree/master/.dockerfiles for the two Dockerfiles in question.

Those dockerfiles would need to run `ponyup update $package nightly` for each of those packages.

**Comment by SeanTAllen** [comment]
Blarg that sucks. Let me open a PR for that.

Other than reverting the change to VERSION. I think this is good to go.

**Comment by SeanTAllen** [comment]
All the versioning, I'll do when I add the automated release process in the next day or so.

**Comment by SeanTAllen** [comment]
@Theodus merged. you can add those issues now.

I'm working on updates for ponyc dockerfiles.

**Pull request merged**
