### PR TITLE
More helpful error if missing lsb_release

### PR DESCRIPTION
**Pull request by 13r0ck**
Just getting started with pony lang for the first time today! Hopefully more actually helpful commits soon!

### CODE REVIEW

**Comment by SeanTAllen** [comment]
What problem does this solve?

**Comment by 13r0ck** [comment]
I was trying to create a pony project while developing in a distrobox container. Most containers do not come with lsb_release by default, so the install fails. Just makes the error more obvious

**Comment by SeanTAllen** [comment]
The case statement isn't an appropriate place to check for that. It would be appropriate to check to see if lsb_release is installed before the command is executed and report back if it isn't. But at that point we are getting into other issues as well such as "what if curl isnt installed?" Having a check for one dependency being missing, but not others doesn't feel great to me.

What did you get as output from running the init script before you installed lsb_release?

I think at minimum it makes sense that we document what tools are required for the script to run. And perhaps before running any command, we check for its existence and print a message if it isn't installed (although that's not particularly "unix-y", but i'm not worried about being "particularly unix-y").

I've used an awful lot of base images for containers and they have all had lsb_release. What is the set of containers that you use that don't contain lsb_release?

**Comment by 13r0ck** [comment]
I tend to agree with all of your points above. Just didn't want to step in suggesting other than the bare minimum for my first PR to the project :)

```
$ distrobox create temp --image fedora:latest
$ distrobox enter temp
$ sh -c "$(curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/ponylang/ponyup/latest-release/ponyup-init.sh)"
sh: line 94: lsb_release: command not found
~~ SNIP ~~
```

I guess it doesn't fail for lsb_release reasons explicitly, but later it does fail without me setting  `ponyup default x86_64-unknown-linux-gnu`, and I mixed those two up in my head.

But a quick check for missing dependencies might be nice anyway!

**Comment by SeanTAllen** [comment]
FYI: `ponyup default x86_64-unknown-linux-gnu` was deprecated a while ago so, those will be some old compiler versions. Are you planning on using Pony with a particular Fedora where having a prebuilt compiler would be helpful?

**Comment by 13r0ck** [comment]
Ah that makes sense why I was having build issues with that. Thank you for the heads up. A deprecation notice for that might be helpful?
I did manage to get ponyc working by installing via [the nix package manager](https://search.nixos.org/packages?channel=23.11&show=ponyc&from=0&size=50&sort=relevance&type=packages&query=ponyc). It looks like that one is old too though. I can make myself useful and update that over there. Sorry for this becoming a longer thread than intended. We can close this, but if you would like me to try opening a PR for either a deps check and/or a deprecation warning on the unknown-linux-gnu, please let me know!

**Comment by SeanTAllen** [comment]
@13r0ck a deprecation notice would be nice. would welcome a PR for that.

is there a particular fedora you are looking to target? if there's a specific version we could look into adding builds for it. i'd need some assistance from you as i dont know fedora well.

**Comment by 13r0ck** [comment]
Will do!

When I am using fedora it is usually in a distrobox container using [fedora:latest](https://hub.docker.com/_/fedora) because I want to do something else that requires newer packages than what ubuntu's repos have. Very much willing to help if I can, but I personally am not looking for a hard and fast prod environment yet

**Comment by SeanTAllen** [comment]
Ok, so, would Fedora 39 work? Given that is what latest is now?

If yes, then what would be needed is the Fedora 39 based version of this Dockerfile:

https://github.com/ponylang/ponyc/blob/main/.ci-dockerfiles/x86-64-unknown-linux-ubuntu22.04-builder/Dockerfile

In particular, the software installation bits. If you can get me a Dockerfile that should match, I can try it out locally as an environment to test and build ponyc in.

Are you on the Zulip? If you are up for helping with the Dockerfile, then coordinating in the zulip here https://ponylang.zulipchat.com/#narrow/stream/190359-ci in the `ci` stream would be the easiest.

**Comment by 13r0ck** [comment]
Will do! I will also move this chat over to zulip once I get that working. Thanks for the chat today, I hope you have a great rest of your weekend!

**Pull request closed without merging**
